config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'oauth/okta_callback'
  get 'oauth/authenticate_okta'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/okta_authentication.rb
class OktaAuthentication < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def okta_callback
    okta_authenticator.receive_authorization_code(params[:code])
  end

  def authenticate_okta
    redirect_to okta_authenticator.authentication_url
  end

  private

  def okta_authenticator
    @okta_authenticator ||= Okta::Authenticator.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/views/home/index.html.erb
<h1>Okta Integration</h1>
<%= link_to "Authenticate Okta", oauth_authenticate_okta_path %>
<br>
<table>
  <th>
    <td>
      Authentication Name
    <td>
    <td>
      Created At
    <td>
    <td>
      Updated At
    <td>
  </th>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OktaIntegrationExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/oauth/okta_callback.html.erb
<p>Successfully connected Okta account</p>